# Generated by Django 4.1.4 on 2022-12-20 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import esc.models


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        null=True, upload_to="avatars", verbose_name="Avatar"
                    ),
                ),
                (
                    "contact_info",
                    models.JSONField(
                        default=esc.models.UserProfile.contact_default,
                        verbose_name="ContactInfo",
                    ),
                ),
                (
                    "favorites",
                    models.JSONField(
                        default=esc.models.UserProfile.favorites_default,
                        verbose_name="Favorites",
                    ),
                ),
                (
                    "booking",
                    models.JSONField(
                        default=esc.models.UserProfile.booking_default,
                        verbose_name="Transactions",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esc.user_role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
            },
        ),
    ]
