# Generated by Django 4.1.4 on 2022-12-20 16:12

from django.db import migrations, models
import esc.models


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0002_user_role_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="favorites",
            new_name="favorite",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="booking",
            field=models.JSONField(
                default=esc.models.UserProfile.booking_default, verbose_name="Bookings"
            ),
        ),
    ]
