# Generated by Django 4.1.4 on 2022-12-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0002_airline_company_airport_country_user_role_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FlightRoute",
        ),
    ]
