# Generated by Django 4.1.4 on 2022-12-20 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import esc.models


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0003_rename_favorites_userprofile_favorite_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airline_Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="IATA Code"
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        max_length=100, null=True, verbose_name="Airline Name"
                    ),
                ),
                (
                    "country",
                    models.TextField(
                        max_length=20, null=True, verbose_name="Base Country"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Manager ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icao_code", models.CharField(max_length=4)),
                ("iata_code", models.CharField(max_length=3)),
                ("display_name", models.CharField(default="", max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("country_name", models.CharField(max_length=50)),
                ("lat_decimal", models.FloatField()),
                ("lon_decimal", models.FloatField()),
            ],
            options={
                "verbose_name": "Airport",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="IATA Code"
                    ),
                ),
                (
                    "name",
                    models.TextField(max_length=20, unique=True, verbose_name="Name"),
                ),
                (
                    "flag",
                    models.TextField(
                        max_length=200, null=True, verbose_name="Flag URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="contact_info",
            field=models.JSONField(
                default=esc.models.UserProfile.contact_default,
                verbose_name="Contact Info",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="esc.user_role",
                verbose_name="Role",
            ),
        ),
        migrations.CreateModel(
            name="FlightRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.IntegerField(default=0)),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esc.airline_company",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Destination_Airport",
                        to="esc.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Origin_Airport",
                        to="esc.airport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.DateTimeField(null=True)),
                ("landing_time", models.DateTimeField(null=True)),
                ("flight_number", models.CharField(max_length=20)),
                ("available_tickets", models.IntegerField(default=100)),
                ("flight_range", models.IntegerField(default=0)),
                (
                    "airline_company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esc.airline_company",
                    ),
                ),
                (
                    "destination_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Destination_airport_Id",
                        to="esc.airport",
                    ),
                ),
                (
                    "origin_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Origin_airport_Id",
                        to="esc.airport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seats", models.IntegerField(default=1)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="esc.flight"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="airport",
            name="country_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="esc.country"
            ),
        ),
    ]
