# Generated by Django 4.1.4 on 2022-12-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0003_delete_flightroute"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ident",
                    models.IntegerField(unique=True, verbose_name="Flight route ID"),
                ),
                ("distance", models.IntegerField(default=0)),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esc.airline_company",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Destination_Airport",
                        to="esc.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Origin_Airport",
                        to="esc.airport",
                    ),
                ),
            ],
        ),
    ]
