# Generated by Django 4.1.4 on 2022-12-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0004_airline_company_airport_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airline_company",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="esc.country",
                verbose_name="Base Country",
            ),
        ),
        migrations.AlterField(
            model_name="airline_company",
            name="name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Airline Name"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.CharField(max_length=200, null=True, verbose_name="Flag URL"),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="Name"),
        ),
    ]
