# Generated by Django 4.1.4 on 2022-12-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0004_flightroute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightroute",
            name="airline",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="esc.airline_company",
            ),
        ),
        migrations.AlterField(
            model_name="flightroute",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Destination_Airport",
                to="esc.airport",
            ),
        ),
        migrations.AlterField(
            model_name="flightroute",
            name="distance",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="flightroute",
            name="ident",
            field=models.IntegerField(
                blank=True, unique=True, verbose_name="Flight route ID"
            ),
        ),
        migrations.AlterField(
            model_name="flightroute",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Origin_Airport",
                to="esc.airport",
            ),
        ),
    ]
