# Generated by Django 4.1.4 on 2022-12-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0005_alter_flightroute_airline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightroute",
            name="distance",
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="flightroute",
            name="ident",
            field=models.IntegerField(
                blank=True, editable=False, unique=True, verbose_name="Flight route ID"
            ),
        ),
    ]
