# Generated by Django 4.1.4 on 2022-12-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0005_alter_airline_company_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airport",
            old_name="country_id",
            new_name="country",
        ),
        migrations.RemoveField(
            model_name="airport",
            name="country_name",
        ),
    ]
