# Generated by Django 4.1.4 on 2022-12-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0006_alter_flightroute_distance_alter_flightroute_ident"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightroute",
            name="distance",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="flightroute",
            name="ident",
            field=models.IntegerField(
                blank=True, unique=True, verbose_name="Flight route ID"
            ),
        ),
    ]
