# Generated by Django 4.1.4 on 2022-12-23 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0008_alter_airline_company_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlattenedFlightRoutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="from to code", max_length=7, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="from to literal", max_length=120
                    ),
                ),
                ("distance", models.IntegerField(blank=True, default=0)),
                (
                    "airlines",
                    models.ManyToManyField(blank=True, to="esc.airline_company"),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Destination",
                        to="esc.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Origin",
                        to="esc.airport",
                    ),
                ),
            ],
        ),
    ]
