# Generated by Django 4.1.4 on 2022-12-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esc", "0009_flattenedflightroutes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flattenedflightroutes",
            options={"verbose_name": "Flight routes by airlines"},
        ),
    ]
